config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/about'

  resources :dogs
  resources :vets
  resources :owners

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vet.rb
class Vet < ApplicationRecord
  has_many :dogs
end

# == Schema Information
#
# Table name: vets
#
#  id         :integer          not null, primary key
#  doctor     :string
#  clinic     :string
#  phone      :string
#  fax        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: [:show, :edit, :update, :destroy]

  # GET /vets
  # GET /vets.json
  def index
    @vets = Vet.all
  end

  # GET /vets/1
  # GET /vets/1.json
  def show
  end

  # GET /vets/new
  def new
    @vet = Vet.new
  end

  # GET /vets/1/edit
  def edit
  end

  # POST /vets
  # POST /vets.json
  def create
    @vet = Vet.new(vet_params)

    respond_to do |format|
      if @vet.save
        format.html { redirect_to @vet, notice: 'Vet was successfully created.' }
        format.json { render :show, status: :created, location: @vet }
      else
        format.html { render :new }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vets/1
  # PATCH/PUT /vets/1.json
  def update
    respond_to do |format|
      if @vet.update(vet_params)
        format.html { redirect_to @vet, notice: 'Vet was successfully updated.' }
        format.json { render :show, status: :ok, location: @vet }
      else
        format.html { render :edit }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vets/1
  # DELETE /vets/1.json
  def destroy
    @vet.destroy
    respond_to do |format|
      format.html { redirect_to vets_url, notice: 'Vet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vet
      @vet = Vet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vet_params
      params.require(:vet).permit(:doctor, :clinic, :phone, :fax)
    end
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/vets/_form.html.erb
<%= simple_form_for(@vet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :doctor %>
    <%= f.input :clinic %>
    <%= f.input :phone %>
    <%= f.input :fax %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vets/edit.html.erb
<h1>Editing Vet</h1>

<%= render 'form', vet: @vet %>

<%= link_to 'Show', @vet %> |
<%= link_to 'Back', vets_path %>

app/views/vets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vets</h1>

<table>
  <thead>
    <tr>
      <th>Doctor</th>
      <th>Clinic</th>
      <th>Phone</th>
      <th>Fax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vets.each do |vet| %>
      <tr>
        <td><%= vet.doctor %></td>
        <td><%= vet.clinic %></td>
        <td><%= vet.phone %></td>
        <td><%= vet.fax %></td>
        <td><%= link_to 'Show', vet %></td>
        <td><%= link_to 'Edit', edit_vet_path(vet) %></td>
        <td><%= link_to 'Destroy', vet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vet', new_vet_path %>

app/views/vets/new.html.erb
<h1>New Vet</h1>

<%= render 'form', vet: @vet %>

<%= link_to 'Back', vets_path %>

app/views/vets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @vet.doctor %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @vet.clinic %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vet.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @vet.fax %>
</p>

<%= link_to 'Edit', edit_vet_path(@vet) %> |
<%= link_to 'Back', vets_path %>